### ISSUE TITLE
Update notation plug-in support to the updated plug-in spec

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#162]
The [feat-kv-extensibility](https://github.com/notaryproject/notation/tree/feat-kv-extensibility) branch was created to validate an early version of the plug-in spec. 
Now that the [plug-in spec](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md), is merged, we need to:

- [x] Take the content from [feat-kv-extensibility](https://github.com/notaryproject/notation/tree/feat-kv-extensibility), and update to reflect the [plug-in spec](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md)
    - Note: the feat-kv-extensibility branch should NOT be updated. It is being used for COSE validations, until COSE support is complete.
    - Updates from the feat-kv-extensibility branch should be PRd to main

To validate, use one of the plug-ins, such as the [Azure Key Vault plug-in](https://github.com/Azure/notation-azure-kv/blob/main/docs/nv2-sign-verify-aks.md). *Which also need to be updated to reflect the updated plug-in spec.*

To complete this work, the following is ready for review:

- [x] [Implement generate signature plugin workflow #42](https://github.com/notaryproject/notation-go/pull/42)
- [x] [Support managing plugin keys #168](https://github.com/notaryproject/notation/pull/168)
- [x] [Add plugin sign capabaility #176](https://github.com/notaryproject/notation/pull/176)
- [x] [Implement new signing spec #18](https://github.com/Azure/notation-azure-kv/pull/18)

**Comment by SteveLasker** [comment]
I've taken the following branches and validated remote signing works with azure keyvault

- [qmuntal/notation at feat-plugin](https://github.com/qmuntal/notation/tree/feat-plugin)
  ```bash
  git clone git@github.com:qmuntal/notation.git
  git checkout feat-plugin
  make install
  cp bin/notation ~/bin/
  ```
- [qmuntal/notation-azure-kv at plugins](https://github.com/qmuntal/notation-azure-kv/tree/plugins)
  ```bash
  git clone git@github.com:qmuntal/notation-azure-kv.git
  git checkout plugins
  go build ./cmd/notation-azure-kv
  cp notation-azure-kv ~/.config/notation/plugins/azure-kv
  ```

Then:
```bash
# Get the signing key from Azure Key Vault
KEY_ID=$(az keyvault certificate show --vault-name wabbit-networks \
                    --name wabbit-networks-io \
                    --query "kid" -o tsv)

# Add the key, note --plugin parameter, but --kms is no longer required
notation key add \
    --name wabbit-networks-io \
    --id $KEY_ID \
    --plugin azure-kv

# Sign the net-monitor image
notation sign --key "wabbit-networks-io" \
  wabbitnetworks.azurecr.io/net-monitor:v1

# View the image and its referers
oras discover -o tree wabbitnetworks.azurecr.io/net-monitor:v1
wabbitnetworks.azurecr.io/net-monitor:v1
└── application/vnd.cncf.notary.v2.signature
    └── sha256:66a3785439035a9b0d7631b2bca6bef0e3944761a9d5a3c28e6360b045ef91c5

# Add the public key for opt-in verification
notation cert add --name "wabbit-networks-io" ./wabbit-networks-io.pem

# verify the image
notation verify wabbitnetworks.azurecr.io/net-monitor:v1
sha256:81a768032a0dcf5fd0d571092d37f2ab31afcac481aa91bb8ea891b0cff8a6ec
```

**Comment by gokarnm** [comment]
This looks great! I've added a comment about `cert add` not being available in RC1 release [here](https://github.com/notaryproject/notation/pull/171#discussion_r872879982), so some of the steps will need updates for RC1.

**Comment by dtzar** [comment]
To try clarify order of PR merge operations - I think it should go:
1. https://github.com/notaryproject/notation-go/pull/42 
These two could go in either order:
2. https://github.com/notaryproject/notation/pull/168
2. https://github.com/notaryproject/notation/pull/176
All the above have to be merged for this one
3. https://github.com/Azure/notation-azure-kv/pull/18

**Comment by qmuntal** [comment]
@SteveLasker can we close this issue? All work is done.
