### ISSUE TITLE
Add COSE support

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#163]
A [prototype of notation cose support](https://github.com/microsoft/notation-cose) has been completed.

This tracks:

- [x] Complete remote signing support: [veraison/go-cose #9](https://github.com/veraison/go-cose/issues/9)
- [ ] Notary Spec support of COSE [#48](https://github.com/notaryproject/notaryproject/pull/148)
- [x] Add support for COSE, through the [veraison/go-cose](https://github.com/veraison/go-cose) project

Other tasks:
- [x] #287
- [x] #288
- [ ] #289
- [ ] #290
- [ ] #291
- [ ] #292 
- [ ] [Refactor code to support multiple envelopes](https://github.com/notaryproject/notation-core-go/issues/24)

**Comment by shizhMSFT** [comment]
The COSE support should be through [notation-core-go](https://github.com/notaryproject/notation-core-go), where `notation-core-go` implements COSE support through the [veraison/go-cose](https://github.com/veraison/go-cose) project.
