### ISSUE TITLE
Tracking issue for pending feedbacks/Issues in PR83(Notation CLI baseline)

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#93]
Tracking issue for multiple comments/issues that were called out in https://github.com/notaryproject/notation/pull/83 and needs to be resolved.

Issues marked with [**Alpha**], must to be resolved for alpha release.(We can discuss about prioritization in next meeting)

### Security
- [x] ~~[**Alpha**] [Don’t take password from CLI in plain text](https://github.com/notaryproject/notation/pull/83#discussion_r709479010); Also taking username and password for each command doesn’t looks like a good UX. (PB: Same as that of https://github.com/notaryproject/notation/issues/119)~~

### Readability & Maintainability
- [x] [**Alpha**] Remove all dead/unused code.
- [x] ~~[**Alpha**] For better readability, at minimum we should to add documentation for important packages and exported names. (PB: Being taken care part of refactoring notation-go and notaiton-core-go)~~
- [x] [**Alpha**] [The package structure should be reorganized for better readability.](https://github.com/notaryproject/notation/pull/83#pullrequestreview-750795888)
- [x] [**Alpha**] Add unit tests. At minimum we need test which exercises positive scenario(successful signing and verification) to avoid breaking changes. (PB: Still valid)
- [x] [Update config.go to export functions instead of exposing internal implementation](https://github.com/notaryproject/notation/pull/83#discussion_r709484002) so that we can modify internals without affecting callers. (PB: Still valid)
- [x] [Move default local file-based signer and verifier implementation to notatio-go-lib](https://github.com/notaryproject/notation/pull/83#discussion_r707814942)

### Usability
- [x] Need better error messages to display in case of failure (PB: Still valid) --> Covered in https://github.com/notaryproject/notation/issues/128
- [x] The CLIs should exit with proper exit code(non zero for failures) [Ref](https://github.com/urfave/cli/blob/master/docs/v2/manual.md#exit-code) (PB: Still valid)
- [x] [**Alpha**] [Verifier CLI should just take list of certs that user trust for verification.](https://github.com/notaryproject/notation/pull/83#discussion_r706386533) No need of separate ca cert param.
- [ ] [Don't overwrite files if file exists unless explicitly indicated by user](https://github.com/notaryproject/notation/pull/83#discussion_r705755110)

### Bugs
- [x] [User shouldn't be able to add two cert/keys with same name](https://github.com/notaryproject/notation/pull/83#discussion_r705937336)

### Nit-picks
- [x] [Move `SignatureDigests` from `path.go` to `cache.go`](https://github.com/notaryproject/notation/pull/83#discussion_r705906444)
- [x] ~~Rename packages to be more relevant: E.g.: [cache.go](https://github.com/notaryproject/notation/pull/83#discussion_r703034639), [list.go](https://github.com/notaryproject/notation/pull/83#discussion_r703041057) (PB: Not required)~~
- [x] ~[Whenever shellingout read both error and std streams](https://github.com/notaryproject/notation/pull/83#discussion_r705752817)~ (PB: Still valid). Replaced with https://github.com/notaryproject/notation/issues/280
- [x] ~~[add 127.0.0.1 for checking localhost ](https://github.com/notaryproject/notation/pull/83#discussion_r704679551)~~ (PB: Still valid) Replaced with https://github.com/notaryproject/notation/issues/279
- [x] [reuse common code between `docker-notation/docker/manifest.go` and `docker-generate/manifest`.](https://github.com/notaryproject/notation/pull/83#discussion_r702618301) (PB: Still valid)

**Comment by dtzar** [comment]
@priteshbandi - taking a quick look, it seems a number of these are resolved.  Can you please update your checklist?  
Remaining items which don't have an issue we can create and put into RC-1.

**Comment by dtzar** [comment]
I migrated the top two issues.  @iamsamirzon once you migrate the bottom three open ones above, we can close this out.

**Comment by iamsamirzon** [comment]
@dtzar  - I migrated the other three issues reported in this catch all into separate issues and am closing this issue,
https://github.com/notaryproject/notation/issues/279
https://github.com/notaryproject/notation/issues/280
https://github.com/notaryproject/notation/issues/281
